language: python
matrix:
  include:
  - name: "3.6 Unit Test"
    python: "3.6-dev"
  - name: "3.7 Unit Test"
    python: "3.7-dev"
install:
  - python3 -m pip install .
script:
  - python3 --version
  - python3 examples/readme_examples.py
