name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.7, 3.8 ]
    name: python-${{ matrix.python }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup python-${{ matrix.python }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tools
        run: |
          python3 -m pip install pylint
          python3 -m pip install mypy
          python3 -m pip install .
      - name: Test
        run: |
          ./test/install_from_local_and_run_code_checks.sh
