name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.6, 3.7, 3.8 ]
    name: python-${{ matrix.python }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup python-${{ matrix.python }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tools
        run: |
          python3 -m pip install pylint
          python3 -m pip install mypy
          python3 -m pip install .
      - name: Test
        run: |
          find undictify -iname "*.py" | grep -v -e "__init__.py" | xargs -L 1 pylint
          find undictify -iname "*.py" | grep -v -e "__init__.py" | xargs -L 1 mypy --strict
          find undictify -iname "*.py" | grep -v -e "__init__.py" | xargs -L 1 python3 -m unittest
          python3 examples/readme_examples.py
